name: modular_bottomsheet
description: Modular bottom sheet with header with ability to scroll
version: 0.0.1
homepage: https://github.com/Ryeori/modular_bottomsheet
repository: https://github.com/Ryeori/modular_bottomsheet

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
